//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCExtractorTester {
    using System;
    
    
    /// <summary>
    ///   Een sterk getypeerde bronklasse waarmee u kunt zoeken naar gelokaliseerde tekenreeksen, enz.
    /// </summary>
    // Deze klasse wordt automatisch gegenereerd met de StronglyTypedResourceBuilder
    // klasse via een hulpprogramma zoals ResGen of Visual Studio.
    // Als u een lid wilt toevoegen of verwijderen, bewerkt u het .ResX-bestand en voert u ResGen opnieuw uit
    // met de optie /str, of u bouwt het VS-project opnieuw.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiffResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiffResources() {
        }
        
        /// <summary>
        ///   Retourneert het exemplaar van ResourceManager dat in het cachegeheugen is opgeslagen en dat wordt gebruikt in deze klasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCExtractorTester.DiffResources", typeof(DiffResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overschrijft de huidige CurrentUICulture-eigenschap voor alle
        ///   bronzoekacties waarvoor deze sterk getypeerde bronklasse wordt gebruikt.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hiermee zoekt u een vertaalde tekenreeks die vergelijkbaar is met .diffBox
        ///{
        ///	margin-left: auto;
        ///	margin-right: auto;
        ///	border: solid 2px #000000;
        ///}
        ///
        ///
        ///.leftPane, .rightPane
        ///{
        ///	float: left;
        ///	width: 50%;
        ///}
        ///
        ///.diffHeader
        ///{
        ///	font-weight: bold;
        ///	padding: 2px 0px 2px 10px;
        ///	background-color: #FFFFFF;
        ///	text-align: center;
        ///}
        ///.diffPane
        ///{
        ///	margin-right: 0px;
        ///	padding: 0px;
        ///	overflow: auto;
        ///	font-family: Courier New;
        ///	font-size: 1em;
        ///}
        ///
        ///.diffTable
        ///{
        ///	width: 100%;
        ///	/*height: 100%;*/
        ///}
        ///
        ///.line
        ///{
        ///	padding-left: .2em;
        ///	white-space: nowrap;
        ///	width: 100%;
        ///}
        ///
        ///.lineNumber
        ///{
        ///	padding: 0 .3em;
        ///	 [rest van de tekenreeks is afgebroken];.
        /// </summary>
        internal static string Diff1 {
            get {
                return ResourceManager.GetString("Diff1", resourceCulture);
            }
        }
    }
}
