
// This file has been generated by the GUI designer. Do not modify.
namespace CCExtractorTester
{
	public partial class AddEntryDialog
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button btnSelectSample;
		private global::Gtk.Button btnSelectResult;
		private global::Gtk.Label lblCmd;
		private global::Gtk.Label lblResult;
		private global::Gtk.Label lblSample;
		private global::Gtk.Entry txtCmd;
		private global::Gtk.Entry txtResult;
		private global::Gtk.Entry txtSample;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget CCExtractorTester.AddEntryDialog
			this.Name = "CCExtractorTester.AddEntryDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Add or edit a entry");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child CCExtractorTester.AddEntryDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnSelectSample = new global::Gtk.Button ();
			this.btnSelectSample.CanFocus = true;
			this.btnSelectSample.Name = "bntSelect";
			this.btnSelectSample.UseUnderline = true;
			this.btnSelectSample.Label = global::Mono.Unix.Catalog.GetString ("Select file");
			this.table1.Add (this.btnSelectSample);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnSelectSample]));
			w2.LeftAttach = ((uint)(2));
			w2.RightAttach = ((uint)(3));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSelectResult = new global::Gtk.Button ();
			this.btnSelectResult.CanFocus = true;
			this.btnSelectResult.Name = "btnSelect";
			this.btnSelectResult.UseUnderline = true;
			this.btnSelectResult.Label = global::Mono.Unix.Catalog.GetString ("Select file");
			this.table1.Add (this.btnSelectResult);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnSelectResult]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblCmd = new global::Gtk.Label ();
			this.lblCmd.Name = "lblCmd";
			this.lblCmd.LabelProp = global::Mono.Unix.Catalog.GetString ("Commands");
			this.table1.Add (this.lblCmd);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblCmd]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblResult = new global::Gtk.Label ();
			this.lblResult.Name = "lblResult";
			this.lblResult.LabelProp = global::Mono.Unix.Catalog.GetString ("Result file");
			this.table1.Add (this.lblResult);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblResult]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblSample = new global::Gtk.Label ();
			this.lblSample.Name = "lblSample";
			this.lblSample.LabelProp = global::Mono.Unix.Catalog.GetString ("Sample file");
			this.table1.Add (this.lblSample);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblSample]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtCmd = new global::Gtk.Entry ();
			this.txtCmd.CanFocus = true;
			this.txtCmd.Name = "txtCmd";
			this.txtCmd.IsEditable = true;
			this.txtCmd.InvisibleChar = '●';
			this.table1.Add (this.txtCmd);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtCmd]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtResult = new global::Gtk.Entry ();
			this.txtResult.CanFocus = true;
			this.txtResult.Name = "txtResult";
			this.txtResult.IsEditable = false;
			this.txtResult.InvisibleChar = '●';
			this.table1.Add (this.txtResult);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtResult]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtSample = new global::Gtk.Entry ();
			this.txtSample.CanFocus = true;
			this.txtSample.Name = "txtSample";
			this.txtSample.IsEditable = false;
			this.txtSample.InvisibleChar = '●';
			this.table1.Add (this.txtSample);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtSample]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Internal child CCExtractorTester.AddEntryDialog.ActionArea
			global::Gtk.HButtonBox w11 = this.ActionArea;
			w11.Name = "dialog1_ActionArea";
			w11.Spacing = 10;
			w11.BorderWidth = ((uint)(5));
			w11.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonCancel]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.buttonOk]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 187;
			this.Show ();
			this.btnSelectResult.Clicked += new global::System.EventHandler (this.OnBtnSelectClicked);
			this.btnSelectSample.Clicked += new global::System.EventHandler (this.OnBntSelectClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
