using System;
using System.Collections.Generic;

namespace CCExtractorTester.Analyzers
{
    /// <summary>
    /// This class holds information about the results that are generated by CCExtractor.
    /// </summary>
	public class RunData {
        /// <summary>
        /// The exit code of CCExtractor at the end.
        /// </summary>
		public int ExitCode { get; set; }

        /// <summary>
        /// The time CCExtractor needed in order to process the sample (or the maximum allowed runtime).
        /// </summary>
		public TimeSpan Runtime { get; set; }

        /// <summary>
        /// A dictionary containing the generated files (keys are the correct files)
        /// </summary>
        public Dictionary<string,string> ResultFiles { get; set; }
	}
}