name: Build Test Suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,17.0)'
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
  
    - name: Restore NuGet Packages
      run: nuget restore ccx_testsuite.sln
 
    - name: Build
      run: msbuild ccx_testsuite.sln /t:ccx_testsuite /p:Platform="x86" /p:Configuration=Release
 
    - name: Prepare artifact upload
      run: mkdir ./artifact; cp CCExtractorTester.exe ./artifact/CCExtractorTester.exe; cp testGenerations.dll ./artifact/testGenerations.dll; cp CommandLine.dll ./artifact/CommandLine.dll
      working-directory: CCExtractorTester\bin\Release\


    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CCExtractorTester suite
        path: CCExtractorTester\bin\Release\artifact
